### ISSUE TITLE
Mock up (create teacher)

### ISSUE THREAD

**Issue by sophimkep** [pnc-virtual-company/2022-G2-VC2-PART2#19]
Design form create teacher

**Comment by Sopha-Rath** [comment]
![Image](https://user-images.githubusercontent.com/96455099/189461797-153112a4-9a3c-4d1d-b337-c45f904d3633.png)

**Comment by him-hey** [comment]
it is ok to me

**Comment by Sopha-Rath** [comment]
Yes, thank you teacher.
