### ISSUE TITLE
Database (ERD)

### ISSUE THREAD

**Issue by sophimkep** [pnc-virtual-company/2022-G2-VC2-PART2#3]
Design database and relationship

**Comment by sarathorn11** [comment]
![Image](https://user-images.githubusercontent.com/90229785/189344884-fa188c90-e8a1-4198-8d5d-86a4812bca51.PNG)

**Comment by sarathorn11** [comment]
![Image](https://user-images.githubusercontent.com/90229785/189508166-d1b0f9ce-d74b-47ff-9838-0dcd64d5951f.png)
