### ISSUE TITLE
Mockup (filter student)

### ISSUE THREAD

**Issue by sophimkep** [pnc-virtual-company/2022-G2-VC2-PART2#40]

**Comment by phandyphorn** [comment]
![Image](https://user-images.githubusercontent.com/90320702/189838189-7fde5864-2819-4f28-8631-ad9cbf96a4bc.png)
![Image](https://user-images.githubusercontent.com/90320702/189838188-0f41ee75-f260-405c-b003-f62681eda13c.png)
